/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Driver.DoublyLinkedListCircular;
import Driver.Drivers;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.AConductores;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.Impresora;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.Principal;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Barillas
 */
public class MenuConductores extends javax.swing.JFrame {

    FileNameExtensionFilter Filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
    
    /**
     * Creates new form MenuConductores
     */
    public MenuConductores() {
        initComponents();
        JFileChooserCargar.setFileFilter(Filtro);
        GenerarImagen();
        Pintar();
    }
     public void GenerarImagen(){
        if(AConductores == null){
            AConductores = new DoublyLinkedListCircular();
        }
        Impresora.Imprimir("Conductores", AConductores.generateDot());
    }
    
    public void Pintar(){
        Image ImagenGrafo = new ImageIcon("Conductores.png").getImage();
        ImagenGrafo.flush();
        Icon Icono = new ImageIcon(ImagenGrafo);
        JLabelReporte.setIcon(Icono);
        JLabelReporte.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFileChooserCargar = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        JComboBoxAccion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        JButtonAccion = new javax.swing.JButton();
        JTextFieldDPI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTextFieldNombres = new javax.swing.JTextField();
        JTextFieldApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTextFieldGenero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTextFieldTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JTextFieldTelefono1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JTextFieldApellidos1 = new javax.swing.JTextField();
        JButtonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLabelReporte = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-----Conductores-----");
        jLabel1.setToolTipText("");

        JComboBoxAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar", "Modificar", "Eliminar", "Graphviz", "Carga Masiva", "Mostrar" }));
        JComboBoxAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxAccionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Accion:");

        JButtonAccion.setText("Realizar");
        JButtonAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAccionActionPerformed(evt);
            }
        });

        JTextFieldDPI.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("DPI:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nombres:");

        JTextFieldNombres.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        JTextFieldApellidos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldApellidosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Genero:");

        JTextFieldGenero.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldGeneroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Telefono:");

        JTextFieldTelefono.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldTelefonoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Direccion:");

        JTextFieldTelefono1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldTelefono1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Licencia");

        JTextFieldApellidos1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldApellidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldApellidos1ActionPerformed(evt);
            }
        });

        JButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JButtonRegresar.setText("Regresar");
        JButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRegresarActionPerformed(evt);
            }
        });

        JLabelReporte.setText("     ");
        jScrollPane1.setViewportView(JLabelReporte);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Fecha:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("DPI Nuevo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JButtonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldApellidos1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldGenero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldTelefono))
                    .addComponent(JButtonAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextFieldDPI)
                            .addComponent(JTextFieldNombres)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JComboBoxAccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(JTextFieldTelefono1)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JComboBoxAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextFieldDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTextFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(JTextFieldApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(JTextFieldTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButtonRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboBoxAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxAccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxAccionActionPerformed

    private void JTextFieldTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldTelefono1ActionPerformed

    private void JTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldTelefonoActionPerformed

    private void JTextFieldGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldGeneroActionPerformed

    private void JButtonAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAccionActionPerformed
        switch(JComboBoxAccion.getSelectedIndex()){
            case 0:{
                String DPI = JTextFieldDPI.getText(),  Name = JTextFieldNombres.getText(), Last_Name = JTextFieldApellidos.getText(),
                        Type_License = JTextFieldApellidos1.getText(), Gender = JTextFieldGenero.getText(), Date = jTextField1.getText(),
                        Phone = JTextFieldTelefono.getText(), Direction = JTextFieldTelefono1.getText();
                if(DPI.equals("") && Name.equals("") && Last_Name.equals("") && Type_License.equals("") && Gender.equals("") && Date.equals("") && Phone.equals("") && Direction.equals("")){
                    JOptionPane.showMessageDialog(null, "Llene todos los campos", "Conductores", JOptionPane.WARNING_MESSAGE);
                }else{
                    try {
                        AConductores.insertLast(new Drivers(DPI, Name, Last_Name, Type_License.charAt(0), Gender, Date, Integer.parseInt(Phone), Direction));
                        JOptionPane.showMessageDialog(null, "Conductor Agregado", "Conductores",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Conductor No Agregado", "Conductores",JOptionPane.ERROR_MESSAGE);
                    }
                }
                jTextField1.setText("");
                JTextFieldTelefono1.setText("");
                JTextFieldTelefono.setText("");
                JTextFieldNombres.setText("");
                JTextFieldGenero.setText("");
                JTextFieldDPI.setText("");
                JTextFieldApellidos1.setText("");
                JTextFieldApellidos.setText("");
                System.out.println("Posicion 1");
                break;
            }
            case 1:{
                String DPI = JTextFieldDPI.getText(), newDPI = jTextField2.getText(), Name = JTextFieldNombres.getText(), Last_Name = JTextFieldApellidos.getText(),
                        Type_License = JTextFieldApellidos1.getText(), Gender = JTextFieldGenero.getText(), Date = jTextField1.getText(),
                        Phone = JTextFieldTelefono.getText(), Direction = JTextFieldTelefono1.getText();
                if(newDPI.equals("") && DPI.equals("") && Name.equals("") && Last_Name.equals("") && Type_License.equals("") && Gender.equals("") && Date.equals("") && Phone.equals("") && Direction.equals("")){
                    JOptionPane.showMessageDialog(null, "Llene todos los campos", "Conductores", JOptionPane.WARNING_MESSAGE);
                }else{
                    try {
                        AConductores.EditDrivers(DPI,newDPI, Name, Last_Name, Type_License.charAt(0), Gender, Date, Integer.parseInt(Phone), Direction);
                        JOptionPane.showMessageDialog(null, "Conductor Editado", "Conductores",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Conductor No Editado", "Conductores",JOptionPane.ERROR_MESSAGE);
                    }
                }
                jTextField1.setText("");
                JTextFieldTelefono1.setText("");
                JTextFieldTelefono.setText("");
                JTextFieldNombres.setText("");
                JTextFieldGenero.setText("");
                JTextFieldDPI.setText("");
                JTextFieldApellidos1.setText("");
                JTextFieldApellidos.setText("");
                jTextField2.setText("");
                System.out.println("Posicion 2");
                break;
            }
            case 2:{
                String DPI = JTextFieldDPI.getText();
                if(DPI.equals("")){
                    JOptionPane.showMessageDialog(null, "Llene el Campo del DPI", "Conductores", JOptionPane.WARNING_MESSAGE);
                }else{
                    try {
                        AConductores.delete(DPI);
                        JOptionPane.showMessageDialog(null, "Conductor Eliminado", "Conductores",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Conductor No Eliminado", "Conductores",JOptionPane.ERROR_MESSAGE);
                    }
                }
                jTextField1.setText("");
                JTextFieldTelefono1.setText("");
                JTextFieldTelefono.setText("");
                JTextFieldNombres.setText("");
                JTextFieldGenero.setText("");
                JTextFieldDPI.setText("");
                JTextFieldApellidos1.setText("");
                JTextFieldApellidos.setText("");
                jTextField2.setText("");
                System.out.println("Posicion 3");
                break;
            }
            case 3:
                GenerarImagen();
                Pintar();
                System.out.println("Posicion 4");
                break;
            case 4:
                JFileChooserCargar.showOpenDialog(this);
                File Archivo = JFileChooserCargar.getSelectedFile();
                if(Archivo != null){
                    if (Archivo.exists()) {
                        try {
                            BufferedReader leer = new BufferedReader(new FileReader(Archivo.getAbsolutePath()));
                            String linea = "";
                            while((linea = leer.readLine()) != null){
                                 
                                String[] partes = linea.split("[\\%]+|;");
                                
                                    AConductores.insertLast(new Drivers(partes[0],partes[1],partes[2], partes[3].charAt(0), partes[4],partes[5],Integer.parseInt(partes[6]), partes[7]));
                                
                            }
                            JOptionPane.showMessageDialog(null, "Llenado de Conductores Exitoso", "Conductores",JOptionPane.INFORMATION_MESSAGE);
                            GenerarImagen();
                            Pintar();
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        } 
                    }else{
                    JOptionPane.showMessageDialog(null, "La direccion de archivo no es valida, archivo inexistente", "Archivo inexistente", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun archivo", "Sin Archivo", JOptionPane.ERROR_MESSAGE);
                }
                System.out.println("Posicon 5");
                break;
            case 5:
                try {
                    AConductores.generatePDF();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun archivo", "Sin Archivo", JOptionPane.ERROR_MESSAGE);
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_JButtonAccionActionPerformed

    private void JTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldApellidosActionPerformed

    private void JTextFieldApellidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldApellidos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldApellidos1ActionPerformed

    private void JButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRegresarActionPerformed
        Principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConductores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAccion;
    private javax.swing.JButton JButtonRegresar;
    private javax.swing.JComboBox<String> JComboBoxAccion;
    private javax.swing.JFileChooser JFileChooserCargar;
    private javax.swing.JLabel JLabelReporte;
    private javax.swing.JTextField JTextFieldApellidos;
    private javax.swing.JTextField JTextFieldApellidos1;
    private javax.swing.JTextField JTextFieldDPI;
    private javax.swing.JTextField JTextFieldGenero;
    private javax.swing.JTextField JTextFieldNombres;
    private javax.swing.JTextField JTextFieldTelefono;
    private javax.swing.JTextField JTextFieldTelefono1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
