/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.BCViajes;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.MEstructuras;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.Principal;
import static edd_proyecto2_201801364_201807100.ImpresoraDot.br;

/**
 *
 * @author Barillas
 */
public class MenuReportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public MenuReportes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JComboBoxReporte = new javax.swing.JComboBox<>();
        JButtonHuffman = new javax.swing.JButton();
        JButtonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JButtonCompleta = new javax.swing.JButton();
        JButtonRutaViaje = new javax.swing.JButton();
        JVerifyAction = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-----------Reportes-----------");

        JComboBoxReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top 10 Viajes Mas Largos", "Top 10 Clientes Con Mas Viajes", "Top 10 Conductores Con Mas Ingresos", "Top 10 Vehiculos" }));

        JButtonHuffman.setText("Encriptar / Desencriptar");
        JButtonHuffman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonHuffmanActionPerformed(evt);
            }
        });

        JButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JButtonRegresar.setText("Regresar");
        JButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRegresarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        JButtonCompleta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JButtonCompleta.setText("Ver Estructura Completa");
        JButtonCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCompletaActionPerformed(evt);
            }
        });

        JButtonRutaViaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JButtonRutaViaje.setText("Ruta de Viaje");
        JButtonRutaViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRutaViajeActionPerformed(evt);
            }
        });

        JVerifyAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Encode", "Decoder" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Ver Grafica de Barras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JButtonCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonRutaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JButtonHuffman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JVerifyAction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JComboBoxReporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JComboBoxReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JVerifyAction, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButtonHuffman, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonRutaViaje, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JButtonCompleta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCompletaActionPerformed
        MEstructuras = new MenuEstructuras();
        MEstructuras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JButtonCompletaActionPerformed

    private void JButtonRutaViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRutaViajeActionPerformed
        
    }//GEN-LAST:event_JButtonRutaViajeActionPerformed

    private void JButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRegresarActionPerformed
        Principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JButtonRegresarActionPerformed

    private void JButtonHuffmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonHuffmanActionPerformed
       switch(JComboBoxReporte.getSelectedIndex()){
           case 0:{
               try {  
                    if(BCViajes != null){
                        if(JVerifyAction.getSelectedIndex() == 0){
                            BCViajes.GenerateReportTopViajes(true);
                            if(br != null){
                                jTextArea1.read(br,null);
                                br.close();
                                jTextArea1.requestFocus();
                            }
                    }else if(JVerifyAction.getSelectedIndex() == 1){
                       BCViajes.GenerateReportTopViajes(false);
                       if(br != null){
                                jTextArea1.read(br,null);
                                br.close();
                                jTextArea1.requestFocus();
                        }
                    }
               }
               } catch (Exception e) {
                   System.out.println(e.getMessage());
               }
               break;
           }
           case 1:{
               try {  
                    if(BCViajes != null){
                        if(JVerifyAction.getSelectedIndex() == 0){
                            BCViajes.GenerateReportTopCustomers(true);
                            if(br != null){
                                jTextArea1.read(br,null);
                                br.close();
                                jTextArea1.requestFocus();
                            }
                    }else if(JVerifyAction.getSelectedIndex() == 1){
                       BCViajes.GenerateReportTopCustomers(false);
                       if(br != null){
                                jTextArea1.read(br,null);
                                br.close();
                                jTextArea1.requestFocus();
                        }
                    }
               }
               } catch (Exception e) {
                   System.out.println(e.getMessage());
               }
               break;
           }
           case 2:{
               try {  
                    if(BCViajes != null){
                        if(JVerifyAction.getSelectedIndex() == 0){
                            BCViajes.GenerateReportTopDrivers(true);
                            if(br != null){
                                jTextArea1.read(br,null);
                                br.close();
                                jTextArea1.requestFocus();
                            }
                    }else if(JVerifyAction.getSelectedIndex() == 1){
                       BCViajes.GenerateReportTopDrivers(false);
                       if(br != null){
                                jTextArea1.read(br,null);
                                br.close();
                                jTextArea1.requestFocus();
                        }
                    }
               }
               } catch (Exception e) {
                   System.out.println(e.getMessage());
               }
               break;
           }
           case 3:{
               try {  
                    if(BCViajes != null){
                        if(JVerifyAction.getSelectedIndex() == 0){
                            BCViajes.GenerateReportTopVehicles(true);
                            if(br != null){
                                jTextArea1.read(br,null);
                                br.close();
                                jTextArea1.requestFocus();
                            }
                    }else if(JVerifyAction.getSelectedIndex() == 1){
                       BCViajes.GenerateReportTopVehicles(false);
                       if(br != null){
                                jTextArea1.read(br,null);
                                br.close();
                                jTextArea1.requestFocus();
                        }
                    }
               }
               } catch (Exception e) {
                   System.out.println(e.getMessage());
               }
               break;
           }
           default:
               break;
       }
    }//GEN-LAST:event_JButtonHuffmanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            switch(JComboBoxReporte.getSelectedIndex()){
                case 0:
                    if(BCViajes != null){
                        BCViajes.GenerarGraficaReportViajes();
                    }else{
                        System.out.println("F");
                    }
                    break;
                case 1:
                    if(BCViajes != null){
                        BCViajes.GenerarGraficaReportCustomers();
                    }else{
                        System.out.println("F");
                    }
                    break;
                case 2:
                    if(BCViajes != null){
                        BCViajes.GenerateGraficaReportDrivers();
                    }else{
                        System.out.println("F");
                    }
                    break;
                case 3:
                    if(BCViajes != null){
                        BCViajes.GenerarGraficaReportVehicles();
                    }else{
                        System.out.println("F");
                    }
                    break;
                default:
                    break;
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCompleta;
    private javax.swing.JButton JButtonHuffman;
    private javax.swing.JButton JButtonRegresar;
    private javax.swing.JButton JButtonRutaViaje;
    private javax.swing.JComboBox<String> JComboBoxReporte;
    private javax.swing.JComboBox<String> JVerifyAction;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
