/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Vehicle.BTree;
import Vehicle.Vehicle;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.AVehiculos;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.Impresora;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.Principal;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Barillas
 */
public class MenuVehiculos extends javax.swing.JFrame {

    FileNameExtensionFilter Filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
    
    /**
     * Creates new form MenuVehiculos
     */
    public MenuVehiculos() {
        initComponents();
        GenerarImagen();
        Pintar();
    }
    
    public void GenerarImagen(){
        if(AVehiculos == null){
            AVehiculos = new BTree<>();
        }
        Impresora.Imprimir("Vehiculos", AVehiculos.GenerateReportTreeB());
    }
    
    public void Pintar(){
        Image ImagenGrafo = new ImageIcon("Vehiculos.png").getImage();
        ImagenGrafo.flush();
        Icon Icono = new ImageIcon(ImagenGrafo);
        JLabelReporte.setIcon(Icono);
        JLabelReporte.repaint();
        
    }
    /**

     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFileChooserCargar = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        JComboBoxAccion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        JButtonAccion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTextFieldModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTextFieldAño = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTextFieldColor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JTextFieldPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JButtonRegresar = new javax.swing.JButton();
        JScrollPaneReporte = new javax.swing.JScrollPane();
        JLabelReporte = new javax.swing.JLabel();
        JTextFieldMarca = new javax.swing.JTextField();
        JTextFieldPlaca = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-----Vehiculos-----");

        JComboBoxAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar", "Modificar", "Eliminar", "Mostrar", "Carga Masiva" }));
        JComboBoxAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxAccionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Accion:");

        JButtonAccion.setText("Realizar");
        JButtonAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAccionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Placa:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Marca:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Modelo:");

        JTextFieldModelo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Año:");

        JTextFieldAño.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldAñoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Color:");

        JTextFieldColor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldColorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Precio:");

        JTextFieldPrecio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldPrecioActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Tipo:");

        JButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JButtonRegresar.setText("Regresar");
        JButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRegresarActionPerformed(evt);
            }
        });

        JScrollPaneReporte.setAutoscrolls(true);
        JScrollPaneReporte.setViewportView(JLabelReporte);

        JTextFieldMarca.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        JTextFieldPlaca.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecanico", "Automatico" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Placa Modify");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JButtonAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JComboBoxAccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTextFieldAño))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTextFieldModelo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTextFieldMarca)
                                    .addComponent(JTextFieldPlaca)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(JTextFieldPrecio)
                                    .addComponent(JTextFieldColor)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JScrollPaneReporte)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JComboBoxAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButtonAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(JTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addComponent(JScrollPaneReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonRegresar)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextFieldAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldAñoActionPerformed

    private void JTextFieldColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldColorActionPerformed

    private void JTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldPrecioActionPerformed

    private void JButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRegresarActionPerformed
        Principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JButtonRegresarActionPerformed

    private void JButtonAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAccionActionPerformed
        switch (JComboBoxAccion.getSelectedIndex()) {
            case 0:{
                String licensePlate = JTextFieldPlaca.getText(), brand = JTextFieldMarca.getText(), model = JTextFieldModelo.getText(),
                        year = JTextFieldAño.getText(), color = JTextFieldColor.getText(),price = JTextFieldPrecio.getText(), type = jComboBox1.getSelectedItem().toString();
                if(licensePlate.equals("") && brand.equals("") && model.equals("") && year.equals("") && color.equals("") && price.equals("")){
                    JOptionPane.showMessageDialog(null, "Llene todos los campos", "Vehiculo", JOptionPane.WARNING_MESSAGE);
                }else{
                    try {
                        AVehiculos.insert(new Vehicle(licensePlate, brand, model, Integer.parseInt(year), color, price, type));
                        JOptionPane.showMessageDialog(null, "Vehiculo Agregado", "Vehiculos",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Vehiculo No Agregado", "Vehiculos",JOptionPane.ERROR_MESSAGE);
                    }
                    
                }
                JTextFieldPlaca.setText("");
                JTextFieldPrecio.setText("");
                JTextFieldModelo.setText("");
                JTextFieldMarca.setText("");
                JTextFieldColor.setText("");
                JTextFieldAño.setText("");
                System.out.println("Entro en el item 0");
                
            break;
            }
            case 1:{
                 String licensePlate = JTextFieldPlaca.getText(), brand = JTextFieldMarca.getText(), model = JTextFieldModelo.getText(),
                        year = JTextFieldAño.getText(), color = JTextFieldColor.getText(),price = JTextFieldPrecio.getText(), type = jComboBox1.getSelectedItem().toString(),
                        licensePlateM = jTextField1.getText();
                if(licensePlateM.equals("")&& licensePlate.equals("") && brand.equals("") && model.equals("") && year.equals("") && color.equals("") && price.equals("")){
                    JOptionPane.showMessageDialog(null, "Llene todos los campos", "Vehiculo", JOptionPane.WARNING_MESSAGE);
                }else{
                    try {
                        AVehiculos.searchForUpdate(new Vehicle(licensePlate), new Vehicle(licensePlateM, brand, model, Integer.parseInt(year), color, price, type));
                        JOptionPane.showMessageDialog(null, "Vehiculo Modificado", "Vehiculos",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Vehiculo No Agregado", "Vehiculos",JOptionPane.ERROR_MESSAGE);
                    }
                    
                }
                JTextFieldPlaca.setText("");
                JTextFieldPrecio.setText("");
                JTextFieldModelo.setText("");
                JTextFieldMarca.setText("");
                JTextFieldColor.setText("");
                JTextFieldAño.setText("");
                jTextField1.setText("");
                System.out.println("Entro en el item 2");
            break;
            }
            case 2:{
                String licensePlate = JTextFieldPlaca.getText();
                if(licensePlate.equals("")){
                    JOptionPane.showMessageDialog(null, "Ingrese la placa a buscar", "Vehiculo", JOptionPane.WARNING_MESSAGE);
                }else{
                    try {
                        AVehiculos.Delete(AVehiculos.search(new Vehicle(licensePlate)));
                        JOptionPane.showMessageDialog(null, "Vehiculo Eliminado", "Vehiculos",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Vehiculo No Agregado", "Vehiculos",JOptionPane.ERROR_MESSAGE);
                    }
                    
                }
                JTextFieldPlaca.setText("");
                JTextFieldPrecio.setText("");
                JTextFieldModelo.setText("");
                JTextFieldMarca.setText("");
                JTextFieldColor.setText("");
                JTextFieldAño.setText("");
                jTextField1.setText("");
                System.out.println("Entro en el item 2");
                break;
            }
            case 3:
                System.out.println("Entro en el item 3");
                GenerarImagen();
                Pintar();
            break;
            case 4:
                JFileChooserCargar.showOpenDialog(this);
                File Archivo = JFileChooserCargar.getSelectedFile();
                if(Archivo != null){
                    if (Archivo.exists()) {
                        try {
                            BufferedReader leer = new BufferedReader(new FileReader(Archivo.getAbsolutePath()));
                            String linea = "";
                            while((linea = leer.readLine()) != null){
                                String[] datos = linea.split(";");
                                String[] partes = datos[0].split(":");
                                AVehiculos.insert(new Vehicle(partes[0], partes[1], partes[2],Integer.parseInt(partes[3]) , partes[4], partes[5], partes[6]));
                            }
                            JOptionPane.showMessageDialog(null, "Llenado de Vehiculos Exitoso", "Vehiculos",JOptionPane.INFORMATION_MESSAGE);
                            GenerarImagen();
                            Pintar();
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        } 
                    }else{
                    JOptionPane.showMessageDialog(null, "La direccion de archivo no es valida, archivo inexistente", "Archivo inexistente", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun archivo", "Sin Archivo", JOptionPane.ERROR_MESSAGE);
                }
            default:
            break;
        }
    }//GEN-LAST:event_JButtonAccionActionPerformed

    private void JComboBoxAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxAccionActionPerformed
        GenerarImagen();
        Pintar();
    }//GEN-LAST:event_JComboBoxAccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAccion;
    private javax.swing.JButton JButtonRegresar;
    private javax.swing.JComboBox<String> JComboBoxAccion;
    private javax.swing.JFileChooser JFileChooserCargar;
    private javax.swing.JLabel JLabelReporte;
    private javax.swing.JScrollPane JScrollPaneReporte;
    private javax.swing.JTextField JTextFieldAño;
    private javax.swing.JTextField JTextFieldColor;
    private javax.swing.JTextField JTextFieldMarca;
    private javax.swing.JTextField JTextFieldModelo;
    private javax.swing.JTextField JTextFieldPlaca;
    private javax.swing.JTextField JTextFieldPrecio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
