//@author Dabs
package Interfaces;

import Customers.Customers;
import Customers.HashTable;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.TClientes;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.Impresora;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.Principal;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.sound.midi.Soundbank;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class MenuClientes extends javax.swing.JFrame {

    FileNameExtensionFilter Filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
    
    /**
     * Creates new form MenuClientes
     */
    public MenuClientes() {
        initComponents();
        JFileChooserCargar.setFileFilter(Filtro);
        GenerarImagen();
        Pintar();
    }
    
    public void GenerarImagen(){
        if(TClientes == null){
            TClientes = new HashTable();
        }
        Impresora.Imprimir("Clientes", TClientes.GenerateReportTablaHash());
    }
    
    public void Pintar(){
        Image ImagenGrafo = new ImageIcon("Clientes.png").getImage();
        ImagenGrafo.flush();
        Icon Icono = new ImageIcon(ImagenGrafo);
        JLabelReporte.setIcon(Icono);
        JLabelReporte.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JComboBoxAccion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTextFieldDPI = new javax.swing.JTextField();
        JTextFieldNombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTextFieldApellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTextFieldGenero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTextFieldTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JTextFieldTelefono1 = new javax.swing.JTextField();
        JButtonAccion = new javax.swing.JButton();
        JButtonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLabelReporte = new javax.swing.JLabel();
        JFileChooserCargar = new javax.swing.JFileChooser();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JComboBoxAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar", "Modificar", "Eliminar", "Graphviz", "Carga Masiva", "Mostrar" }));
        JComboBoxAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxAccionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("------Clientes------");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Accion:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("DPI:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nombres:");

        JTextFieldDPI.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        JTextFieldNombres.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Apellidos:");

        JTextFieldApellidos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Genero:");

        JTextFieldGenero.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldGeneroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Telefono:");

        JTextFieldTelefono.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldTelefonoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Direccion:");

        JTextFieldTelefono1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTextFieldTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldTelefono1ActionPerformed(evt);
            }
        });

        JButtonAccion.setText("Realizar");
        JButtonAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAccionActionPerformed(evt);
            }
        });

        JButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JButtonRegresar.setText("Regresar");
        JButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRegresarActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        JLabelReporte.setText("     ");
        jScrollPane1.setViewportView(JLabelReporte);

        JFileChooserCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFileChooserCargarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fecha:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTextFieldApellidos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTextFieldGenero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTextFieldTelefono))
                            .addComponent(JButtonAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTextFieldNombres)
                                    .addComponent(JTextFieldDPI)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JComboBoxAccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTextFieldTelefono1)
                                    .addComponent(jTextField1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JButtonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JComboBoxAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonAccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(JTextFieldDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTextFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(JTextFieldTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButtonRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboBoxAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxAccionActionPerformed
        
    }//GEN-LAST:event_JComboBoxAccionActionPerformed

    private void JTextFieldGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldGeneroActionPerformed

    private void JTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldTelefonoActionPerformed

    private void JTextFieldTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldTelefono1ActionPerformed

    private void JButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRegresarActionPerformed
        Principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JButtonRegresarActionPerformed

    private void JButtonAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAccionActionPerformed
        switch(JComboBoxAccion.getSelectedIndex()){
            case 0:{
                String DPI = JTextFieldDPI.getText(), Name = JTextFieldNombres.getText(), Last_Name = JTextFieldApellidos.getText(),
                        Gender = JTextFieldGenero.getText(), Date = jTextField1.getText(), Phone = JTextFieldTelefono.getText(),
                        Direction = JTextFieldTelefono1.getText();
                if(DPI.equals("") && Name.equals("") && Last_Name.equals("") && Gender.equals("") && Date.equals("") && Phone.equals("") && Direction.equals("")){
                     JOptionPane.showMessageDialog(null, "Llene todos los campos", "Clientes", JOptionPane.WARNING_MESSAGE);
                }else{
                    try {
                        TClientes.InsertNode(new Customers(DPI, Name, Last_Name, Gender, Date, Integer.parseInt(Phone), Direction));
                        JOptionPane.showMessageDialog(null, "Cliente Agregado", "Clientes",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Cliente No Agregado", "Clientes",JOptionPane.ERROR_MESSAGE);
                    }
                }
                jTextField1.setText("");
                JTextFieldTelefono1.setText("");
                JTextFieldTelefono.setText("");
                JTextFieldNombres.setText("");
                JTextFieldGenero.setText("");
                JTextFieldDPI.setText("");
                JTextFieldApellidos.setText("");
                System.out.println("posicion 0");
                break;
            }
            case 1:{
                String DPI = JTextFieldDPI.getText(), Name = JTextFieldNombres.getText(), Last_Name = JTextFieldApellidos.getText(),
                        Gender = JTextFieldGenero.getText(), Date = jTextField1.getText(), Phone = JTextFieldTelefono.getText(),
                        Direction = JTextFieldTelefono1.getText();
                if(DPI.equals("") && Name.equals("") && Last_Name.equals("") && Gender.equals("") && Date.equals("") && Phone.equals("") && Direction.equals("")){
                     JOptionPane.showMessageDialog(null, "Llene todos los campos", "Clientes", JOptionPane.WARNING_MESSAGE);
                }else{
                    try {
                        TClientes.EditNode(DPI, Name, Last_Name, Gender, Date, Integer.parseInt(Phone), Direction);
                        JOptionPane.showMessageDialog(null, "Cliente Modificado", "Clientes",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Cliente No Modificado", "Clientes",JOptionPane.ERROR_MESSAGE);
                    }
                }
                jTextField1.setText("");
                JTextFieldTelefono1.setText("");
                JTextFieldTelefono.setText("");
                JTextFieldNombres.setText("");
                JTextFieldGenero.setText("");
                JTextFieldDPI.setText("");
                JTextFieldApellidos.setText("");
                System.out.println("Posicion1");
                break;
            }
            case 2:{
                String DPI = JTextFieldDPI.getText();
                if(DPI.equals("")){
                     JOptionPane.showMessageDialog(null, "Llene el campo del DPI", "Clientes", JOptionPane.WARNING_MESSAGE);
                }else{
                    try {
                        TClientes.DeleteNode(DPI);
                        JOptionPane.showMessageDialog(null, "Cliente Eliminado", "Clientes",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Cliente No Modificado", "Clientes",JOptionPane.ERROR_MESSAGE);
                    }
                }
                jTextField1.setText("");
                JTextFieldTelefono1.setText("");
                JTextFieldTelefono.setText("");
                JTextFieldNombres.setText("");
                JTextFieldGenero.setText("");
                JTextFieldDPI.setText("");
                JTextFieldApellidos.setText("");
                System.out.println("Posicion2");
                break;
            }
            case 3:
                GenerarImagen();
                Pintar();
                System.out.println("Posicion3");
                break;
            case 4:
                JFileChooserCargar.showOpenDialog(this);
                File Archivo = JFileChooserCargar.getSelectedFile();
                if(Archivo != null){
                    if (Archivo.exists()) {
                        try {
                            BufferedReader leer = new BufferedReader(new FileReader(Archivo.getAbsolutePath()));
                            String linea = "";
                            while((linea = leer.readLine()) != null){
                                 
                                String[] partes = linea.split("[,]+|;");
                                if(partes.length <= 7){
                                    TClientes.InsertNode(new Customers(partes[0],partes[1], partes[2],partes[3],partes[4],Integer.parseInt(partes[5]),partes[6]));
                                }else{
                                    TClientes.InsertNode(new Customers(partes[0],partes[1],partes[2],partes[3],Integer.parseInt(partes[4]),partes[5]));
                                }
                                
                            }
                            JOptionPane.showMessageDialog(null, "Llenado de Clients Exitoso", "Clientes",JOptionPane.INFORMATION_MESSAGE);
                            GenerarImagen();
                            Pintar();
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        } 
                    }else{
                    JOptionPane.showMessageDialog(null, "La direccion de archivo no es valida, archivo inexistente", "Archivo inexistente", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun archivo", "Sin Archivo", JOptionPane.ERROR_MESSAGE);
                }
                System.out.println("Posicion4");
                break;
            case 5:
                try {
                   TClientes.generatePDF();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun archivo", "Sin Archivo", JOptionPane.ERROR_MESSAGE);
                }
                break;
            default:
               break;
        }
    }//GEN-LAST:event_JButtonAccionActionPerformed

    private void JFileChooserCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFileChooserCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFileChooserCargarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAccion;
    private javax.swing.JButton JButtonRegresar;
    private javax.swing.JComboBox<String> JComboBoxAccion;
    private javax.swing.JFileChooser JFileChooserCargar;
    private javax.swing.JLabel JLabelReporte;
    private javax.swing.JTextField JTextFieldApellidos;
    private javax.swing.JTextField JTextFieldDPI;
    private javax.swing.JTextField JTextFieldGenero;
    private javax.swing.JTextField JTextFieldNombres;
    private javax.swing.JTextField JTextFieldTelefono;
    private javax.swing.JTextField JTextFieldTelefono1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
