//@author Dabs
package Interfaces;
import Viajes.BlockChain;
import Viajes.Viaje;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.MClientes;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.MVehiculos;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.BCViajes;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.MConductores;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.MReportes;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.MRutas;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.MViajes;
import static edd_proyecto2_201801364_201807100.EDD_PROYECTO2_201801364_201807100.Mapa;
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        Image ImagenGrafo = new ImageIcon("Mapa.png").getImage();
        Icon Icono = new ImageIcon(ImagenGrafo.getScaledInstance(JLabelReporte.getWidth(), JLabelReporte.getHeight(), Image.SCALE_SMOOTH));
        JLabelReporte.setIcon(Icono);
        JLabelReporte.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonClientes = new javax.swing.JButton();
        ButtonVehiculos = new javax.swing.JButton();
        ButtonConductores = new javax.swing.JButton();
        ButtonRutas = new javax.swing.JButton();
        ButtonViajes = new javax.swing.JButton();
        ButtonReportes = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JLabelReporte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonClientes.setText("Clientes");
        ButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientesActionPerformed(evt);
            }
        });

        ButtonVehiculos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonVehiculos.setText("Vehiculos");
        ButtonVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVehiculosActionPerformed(evt);
            }
        });

        ButtonConductores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonConductores.setText("Conductores");
        ButtonConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConductoresActionPerformed(evt);
            }
        });

        ButtonRutas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonRutas.setText("Rutas");
        ButtonRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRutasActionPerformed(evt);
            }
        });

        ButtonViajes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonViajes.setText("Viajes");
        ButtonViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonViajesActionPerformed(evt);
            }
        });

        ButtonReportes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonReportes.setText("Reportes");
        ButtonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReportesActionPerformed(evt);
            }
        });

        ButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(java.awt.SystemColor.control);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Universidad San Carlos De Guatemala\nFacultad De Ingenieria\nEscuela de Ciencias y Sistemas\nEstructura de Datos\nVacaciones Junio 2020\n\nJuan Daniel Enrique Roman Barrientos - 201801364\nDaniel Alejandro Barillas Soberanis - 201807100");
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonVehiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(ButtonConductores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(ButtonRutas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(ButtonViajes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(ButtonReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(ButtonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonVehiculos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonConductores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonRutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonViajes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonReportes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRutasActionPerformed
        if(MRutas == null){
            MRutas = new MenuRutas();
        }
        MRutas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonRutasActionPerformed

    private void ButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientesActionPerformed
        if(MClientes == null){
            MClientes = new MenuClientes();
        }
        MClientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonClientesActionPerformed

    private void ButtonVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVehiculosActionPerformed
        if(MVehiculos == null){
            MVehiculos = new MenuVehiculos();
        }
        MVehiculos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonVehiculosActionPerformed

    private void ButtonConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConductoresActionPerformed
       if(MConductores == null){
            MConductores = new MenuConductores();
        }
        MConductores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonConductoresActionPerformed

    private void ButtonViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonViajesActionPerformed
        if(MViajes == null){
            MViajes = new MenuViajes();
        }
        MViajes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonViajesActionPerformed

    private void ButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReportesActionPerformed
        if(MReportes==null){
            MReportes = new MenuReportes();
        }
        MReportes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClientes;
    private javax.swing.JButton ButtonConductores;
    private javax.swing.JButton ButtonReportes;
    private javax.swing.JButton ButtonRutas;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JButton ButtonVehiculos;
    private javax.swing.JButton ButtonViajes;
    private javax.swing.JLabel JLabelReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
